<?php

namespace Database\Seeders;

use App\Models\Embedding;
use App\Models\SourceTable;
use App\Models\SourceTableColumn;
use Illuminate\Database\Seeder;

/**
 * EmbeddingSeeder
 *
 * Seeds the `embeddings` table with sample 384-dimension vector embeddings
 * for all registered databases, tables, and their aliases.
 *
 * In production, these vectors would be generated by the Python
 * sentence-transformers script. This seeder creates deterministic mock
 * vectors for development and testing purposes.
 *
 * Usage:
 *   php artisan db:seed --class=EmbeddingSeeder
 *
 * The vectors are generated using a seeded pseudo-random approach so they
 * are deterministic across runs but still provide meaningful similarity
 * distributions for testing the ContextRouter.
 */
class EmbeddingSeeder extends Seeder
{
    /**
     * Total dimensions for the embedding vectors (all-MiniLM-L6-v2 output).
     */
    protected const DIMENSIONS = 384;

    /**
     * Seed type groups with consistent random seeds.
     * Each group gets a unique seed so similar entities have similar vectors.
     */
    protected const SEED_GROUPS = [
        'customer'    => 42,
        'product'     => 123,
        'sales'       => 256,
        'employee'    => 389,
        'supplier'    => 512,
        'people'      => 645,   // customers, employees share "people" traits
        'inventory'   => 778,   // products, suppliers share "inventory" traits
        'transaction' => 901,   // sales is transaction-oriented
    ];

    /**
     * Run the database seeds.
     *
     * Seeds embeddings in order:
     *   1. Database-level embeddings (db_01 through db_05)
     *   2. Table-level embeddings (customers, products, sales, employees, suppliers)
     *   3. Alias embeddings (client→customers, staff→employees, etc.)
     *   4. Query type embeddings (select, count, aggregate, filtered_search)
     */
    public function run(): void
    {
        $this->command->info('🌱 Seeding embeddings...');

        $this->seedDatabaseEmbeddings();
        $this->seedTableEmbeddings();
        $this->seedAliasEmbeddings();
        $this->seedQueryTypeEmbeddings();

        $this->command->info('✅ Embeddings seeded successfully.');
    }

    // ─── Database-Level Embeddings ───

    /**
     * Seed embeddings for each database connection with its semantic description.
     *
     * Each database embedding captures the overall purpose and content of that source,
     * enabling the ContextRouter to route queries like "show customer info" to db_01.
     */
    protected function seedDatabaseEmbeddings(): void
    {
        $databases = config('chatbot.sources', []);

        foreach ($databases as $sourceId => $config) {
            $description = $config['description'] ?? '';
            $tables      = implode(', ', $config['tables'] ?? []);

            // Build a rich text that captures the semantic meaning of this database
            $text = "{$description}. Contains tables: {$tables}. ";

            // Add column context for richer embeddings
            $columns = $this->getSourceColumnSummary($sourceId);
            if (!empty($columns)) {
                $text .= "Available columns across all tables: {$columns}.";
            }

            $embedding = $this->generateMockEmbedding($text, self::SEED_GROUPS[$sourceId] ?? crc32($sourceId));

            Embedding::updateOrCreate(
                [
                    'entity_type' => 'database',
                    'entity_key'  => $sourceId,
                ],
                [
                    'entity_name' => strtoupper($sourceId) . ' - ' . ($config['label'] ?? $config['description'] ?? ''),
                    'source_id'   => $sourceId,
                    'embedding'   => $embedding,
                    'metadata'    => [
                        'description'   => $description,
                        'tables'        => $config['tables'] ?? [],
                        'seed_group'    => self::SEED_GROUPS[$sourceId] ?? null,
                        'generated_by'  => 'EmbeddingSeeder',
                        'generated_at'  => now()->toIso8601String(),
                    ],
                ]
            );

            $this->command->line("   ✅ Database embedding: {$sourceId}");
        }
    }

    // ─── Table-Level Embeddings ───

    /**
     * Seed embeddings for each registered table.
     *
     * Table embeddings include the table name, its aliases, and its columns.
     * This allows queries like "show me all client names and emails" to match
     * semantically to the "customers" table.
     */
    protected function seedTableEmbeddings(): void
    {
        $tables = SourceTable::all();

        foreach ($tables as $table) {
            // Gather column names for this table
            $columns = SourceTableColumn::where('table_name', $table->table_name)
                ->pluck('column_name')
                ->toArray();

            // Gather aliases
            $aliases = array_filter(array_map('trim', explode(',', $table->alias ?? '')));

            // Build rich semantic text
            $parts = ["Table {$table->table_name}"];

            if (!empty($aliases)) {
                $parts[] = 'also referred to as ' . implode(', ', $aliases);
            }

            if (!empty($columns)) {
                $parts[] = 'has columns: ' . implode(', ', $columns);
            }

            // Add domain-specific context
            $domainContext = $this->getTableDomainContext($table->table_name, $columns);
            if ($domainContext) {
                $parts[] = $domainContext;
            }

            $text = implode('. ', $parts) . '.';

            // Use a stable seed so same tables always get similar vectors
            $seed = crc32($table->table_name);
            $embedding = $this->generateMockEmbedding($text, $seed);

            Embedding::updateOrCreate(
                [
                    'entity_type' => 'table',
                    'entity_key'  => $table->table_name,
                ],
                [
                    'entity_name' => ucfirst(str_replace('_', ' ', $table->table_name)) . ' Table',
                    'source_id'   => $table->source_id,
                    'embedding'   => $embedding,
                    'metadata'    => [
                        'columns'       => $columns,
                        'aliases'       => $aliases,
                        'source_id'     => $table->source_id,
                        'generated_by'  => 'EmbeddingSeeder',
                        'generated_at'  => now()->toIso8601String(),
                    ],
                ]
            );

            $this->command->line("   ✅ Table embedding: {$table->table_name}");
        }
    }

    // ─── Alias Embeddings ───

    /**
     * Seed embeddings for table aliases.
     *
     * Alias embeddings map alternative names (client, staff, goods) to their
     * canonical tables. This enables natural language queries like "show clients"
     * to route to the "customers" table via semantic similarity.
     *
     * Aliases seeded:
     *   clients    → customers  (db_01)
     *   buyer      → customers  (db_01)
     *   item       → products   (db_02)
     *   goods      → products   (db_02)
     *   order      → sales      (db_03)
     *   staff      → employees  (db_04)
     *   vendor     → suppliers  (db_05)
     */
    protected function seedAliasEmbeddings(): void
    {
        // Define alias mappings with semantic context
        $aliasMap = $this->getAliasMap();

        foreach ($aliasMap as $alias => $config) {
            $tableName  = $config['table'];
            $sourceId   = $config['source'];
            $context    = $config['context'];
            $aliasKey   = "{$tableName}:alias:{$alias}";

            $text = "{$alias} refers to the {$tableName} table. {$context}";

            $seed = crc32($aliasKey);
            $embedding = $this->generateMockEmbedding($text, $seed);

            Embedding::updateOrCreate(
                [
                    'entity_type' => 'alias',
                    'entity_key'  => $aliasKey,
                ],
                [
                    'entity_name' => "{$alias} → {$tableName}",
                    'source_id'   => $sourceId,
                    'embedding'   => $embedding,
                    'metadata'    => [
                        'alias'           => $alias,
                        'canonical_table' => $tableName,
                        'source_id'       => $sourceId,
                        'context'         => $context,
                        'generated_by'    => 'EmbeddingSeeder',
                        'generated_at'    => now()->toIso8601String(),
                    ],
                ]
            );

            $this->command->line("   ✅ Alias embedding: {$alias} → {$tableName}");
        }
    }

    // ─── Query Type Embeddings ───

    /**
     * Seed embeddings for query type classification.
     *
     * These enable the ContextRouter to detect the user's intent:
     * - "show customers" → select
     * - "count products" → count
     * - "total sales"   → aggregate
     * - "find where..." → filtered_search
     */
    protected function seedQueryTypeEmbeddings(): void
    {
        $types = config('chatbot.query_types', []);

        foreach ($types as $type) {
            $text = $type['description'];

            $seed = crc32($type['name']);
            $embedding = $this->generateMockEmbedding($text, $seed);

            Embedding::updateOrCreate(
                [
                    'entity_type' => 'query_type',
                    'entity_key'  => $type['name'],
                ],
                [
                    'entity_name' => ucfirst($type['name']) . ' Query',
                    'source_id'   => null,
                    'embedding'   => $embedding,
                    'metadata'    => [
                        'description'  => $type['description'],
                        'generated_by' => 'EmbeddingSeeder',
                        'generated_at' => now()->toIso8601String(),
                    ],
                ]
            );

            $this->command->line("   ✅ Query type embedding: {$type['name']}");
        }
    }

    // ─── Mock Vector Generation ───

    /**
     * Generate a deterministic 384-dimension mock embedding vector.
     *
     * Uses a seeded pseudo-random approach so identical inputs always
     * produce identical vectors. The vector is L2-normalized to unit length
     * matching the behavior of real sentence-transformers output.
     *
     * @param  string $text     Input text to derive the embedding from
     * @param  int    $seed     Deterministic seed for reproducibility
     * @return array<int, float>  384 normalized float values
     */
    protected function generateMockEmbedding(string $text, int $seed): array
    {
        // Use a seeded RNG for deterministic output
        srand($seed);

        $vector = [];

        // Generate 384 pseudo-random values
        for ($i = 0; $i < self::DIMENSIONS; $i++) {
            // Box-Muller transform for approximately normal distribution
            $u1 = mt_rand() / mt_getrandmax();
            $u2 = mt_rand() / mt_getrandmax();

            $radius = sqrt(-2 * log(max($u1, 1e-10)));
            $theta  = 2 * M_PI * $u2;

            $vector[] = $radius * cos($theta);
        }

        // L2-normalize to unit length (matches sentence-transformers behavior)
        $norm = sqrt(array_sum(array_map(fn($v) => $v * $v, $vector)));

        if ($norm > 0) {
            foreach ($vector as $i => $val) {
                $vector[$i] = round($val / $norm, 10);
            }
        }

        return $vector;
    }

    // ─── Helpers ───

    /**
     * Get a summary of all columns across all tables in a source.
     */
    protected function getSourceColumnSummary(string $sourceId): string
    {
        $tables = SourceTable::where('source_id', $sourceId)->pluck('table_name');
        $allColumns = [];

        foreach ($tables as $table) {
            $cols = SourceTableColumn::where('table_name', $table)
                ->pluck('column_name')
                ->toArray();
            $allColumns = array_merge($allColumns, $cols);
        }

        return implode(', ', array_unique($allColumns));
    }

    /**
     * Get domain-specific context for a table to enrich its embedding text.
     */
    protected function getTableDomainContext(string $tableName, array $columns): string
    {
        $contexts = [
            'customers' => 'Used for customer relationship management, sales targeting, and contact lookup.',
            'products'  => 'Used for inventory management, pricing analysis, and stock tracking.',
            'sales'     => 'Used for revenue analysis, sales performance tracking, and order history.',
            'employees' => 'Used for HR management, payroll processing, and department reporting.',
            'suppliers' => 'Used for vendor management, supply chain tracking, and procurement.',
        ];

        return $contexts[$tableName] ?? '';
    }

    /**
     * Get the complete alias mapping with semantic context.
     *
     * @return array<string, array{table: string, source: string, context: string}>
     */
    protected function getAliasMap(): array
    {
        return [
            'clients' => [
                'table'   => 'customers',
                'source'  => 'db_01',
                'context' => 'Used to look up people who purchase products or services.',
            ],
            'buyer' => [
                'table'   => 'customers',
                'source'  => 'db_01',
                'context' => 'A person or entity that purchases goods or services.',
            ],
            'item' => [
                'table'   => 'products',
                'source'  => 'db_02',
                'context' => 'Individual product units kept in inventory for sale.',
            ],
            'goods' => [
                'table'   => 'products',
                'source'  => 'db_02',
                'context' => 'Merchandise or supplies held for sale to customers.',
            ],
            'order' => [
                'table'   => 'sales',
                'source'  => 'db_03',
                'context' => 'Records of customer purchases and transaction history.',
            ],
            'staff' => [
                'table'   => 'employees',
                'source'  => 'db_04',
                'context' => 'People employed by the organization across various departments.',
            ],
            'vendor' => [
                'table'   => 'suppliers',
                'source'  => 'db_05',
                'context' => 'Companies that supply products or materials to the business.',
            ],
        ];
    }
}
