[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /Users/zesan/Desktop/Entrepreneurs_Automation/multi-source-chatbot/artisan queue:work database --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=zesan
numprocs=4
redirect_stderr=true
stdout_logfile=/Users/zesan/Desktop/Entrepreneurs_Automation/multi-source-chatbot/storage/logs/worker.log
stopwaitsecs=3600

[program:laravel-horizon]
process_name=%(program_name)s
command=php /Users/zesan/Desktop/Entrepreneurs_Automation/multi-source-chatbot/artisan horizon
autostart=true
autorestart=true
user=zesan
redirect_stderr=true
stdout_logfile=/Users/zesan/Desktop/Entrepreneurs_Automation/multi-source-chatbot/storage/logs/horizon.log
stopwaitsecs=3600
