<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', 'Helvetica Neue', Arial, sans-serif;
            font-size: 11px;
            color: #1e293b;
            line-height: 1.4;
            margin: 0;
            padding: 20px;
        }
        .header {
            border-bottom: 2px solid #2563eb;
            padding-bottom: 12px;
            margin-bottom: 16px;
        }
        .header h1 {
            font-size: 18px;
            color: #1e3a8a;
            margin: 0 0 4px 0;
        }
        .meta-info {
            font-size: 9px;
            color: #64748b;
        }
        .summary-grid {
            margin-bottom: 20px;
            border-collapse: collapse;
            width: 100%;
        }
        .summary-grid td {
            padding: 6px 10px;
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            font-size: 10px;
        }
        .summary-label {
            font-weight: bold;
            color: #334155;
            width: 30%;
        }
        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .data-table th {
            background-color: #1e40af;
            color: #ffffff;
            font-weight: bold;
            padding: 8px 6px;
            text-align: left;
            font-size: 10px;
            border: 1px solid #1e40af;
        }
        .data-table td {
            padding: 6px;
            border: 1px solid #e2e8f0;
            font-size: 9.5px;
        }
        .data-table tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .footer {
            margin-top: 30px;
            font-size: 8px;
            color: #94a3b8;
            text-align: center;
            border-top: 1px solid #e2e8f0;
            padding-top: 8px;
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            font-size: 8px;
            border-radius: 4px;
            background-color: #eff6ff;
            color: #1d4ed8;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <div class="meta-info">
            Generated by AI Multi-Source Analytics Engine &bull; Timestamp: {{ $timestamp }}
        </div>
    </div>

    @if(!empty($summary))
        <table class="summary-grid">
            @foreach($summary as $key => $val)
                <tr>
                    <td class="summary-label">{{ $key }}</td>
                    <td>{{ is_array($val) ? json_encode($val) : $val }}</td>
                </tr>
            @endforeach
        </table>
    @endif

    @if(!empty($headers) && !empty($rows))
        <table class="data-table">
            <thead>
                <tr>
                    @foreach($headers as $header)
                        <th>{{ $header }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach($rows as $row)
                    <tr>
                        @foreach($row as $cell)
                            <td>{{ is_array($cell) ? json_encode($cell) : $cell }}</td>
                        @endforeach
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <div class="footer">
        Confidential &bull; Multi-Source Chatbot & Business Analytics AI Platform &bull; Page 1 of 1
    </div>
</body>
</html>
