[program:chatbot-crm]
process_name=%(program_name)s_%(process_num)02d
command=php /home/entrepre/chat.entrepreneursautomation.com/artisan queue:work database --queue=crm --tries=3 --backoff=10 --memory=256 --sleep=3 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=entrepre
numprocs=1
redirect_stderr=true
stdout_logfile=/home/entrepre/chat.entrepreneursautomation.com/storage/logs/supervisor-crm.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
