<?php

declare(strict_types=1);

namespace App\Services\AI;

use App\AI\Routing\RouteType;
use App\Models\Conversation;
use App\Services\AI\DTOs\ContextualResolutionResult;
use App\Services\AI\DTOs\FollowUpDecision;

/**
 * Deterministic Policy Manager for Selective Follow-Up.
 *
 * Invariant: The LLM agent proposes a follow-up; Laravel deterministically decides whether it is ALLOWED or SUPPRESSED.
 */
class FollowUpPolicyManager
{
    /**
     * Supported follow-up category taxonomy.
     */
    public const SUPPORTED_TYPES = [
        'purchase_interest',
        'product_variant',
        'delivery',
    ];

    /**
     * Evaluate a proposed follow-up against deterministic business safety and conversational invariants.
     *
     * @param string $rawAnswer Direct answer generated by the agent
     * @param string|null $proposedFollowUp Proposed follow-up question
     * @param string|null $followUpType Category type of follow-up
     * @param RouteType|string $route Current routing decision
     * @param string $userQuery User's inbound query
     * @param Conversation|null $conversation Current conversation model
     * @param ContextualResolutionResult|null $contextResult Contextual query resolution result
     * @param object|null $answerabilityDecision SemanticAnswerabilityGate decision (if applicable)
     */
    public function evaluate(
        string $rawAnswer,
        ?string $proposedFollowUp,
        ?string $followUpType,
        RouteType|string $route,
        string $userQuery,
        ?Conversation $conversation = null,
        ?ContextualResolutionResult $contextResult = null,
        ?object $answerabilityDecision = null,
    ): FollowUpDecision {
        $cleanAnswer = trim($rawAnswer);
        $cleanFollowUp = !empty($proposedFollowUp) ? trim($proposedFollowUp) : null;
        $cleanType = !empty($followUpType) ? strtolower(trim($followUpType)) : null;

        $routeStr = is_string($route) ? strtolower($route) : $route->value;

        // 1. Empty or Null Proposal Check
        if ($cleanFollowUp === null || $cleanFollowUp === '') {
            return new FollowUpDecision(
                allowed: false,
                answer: $cleanAnswer,
                suppressionReason: 'no_proposal'
            );
        }

        // 2. Unsupported Type Check
        if ($cleanType === null || !in_array($cleanType, self::SUPPORTED_TYPES, true)) {
            return new FollowUpDecision(
                allowed: false,
                answer: $cleanAnswer,
                followUpText: $cleanFollowUp,
                followUpType: $cleanType,
                suppressionReason: 'unsupported_type'
            );
        }

        // 3. Hard Route Boundaries (Only KNOWLEDGE and CHAT permitted)
        if ($routeStr !== 'knowledge' && $routeStr !== 'chat') {
            return new FollowUpDecision(
                allowed: false,
                answer: $cleanAnswer,
                followUpText: $cleanFollowUp,
                followUpType: $cleanType,
                suppressionReason: 'unauthorized_route_' . $routeStr
            );
        }

        // 4. Grounding & Confidence Check for KNOWLEDGE route
        if ($routeStr === 'knowledge' && $answerabilityDecision !== null) {
            $isConfident = method_exists($answerabilityDecision, 'isConfident')
                ? $answerabilityDecision->isConfident()
                : (is_array($answerabilityDecision) && ($answerabilityDecision['status'] ?? '') === 'CONFIDENT');

            if (!$isConfident) {
                return new FollowUpDecision(
                    allowed: false,
                    answer: $cleanAnswer,
                    followUpText: $cleanFollowUp,
                    followUpType: $cleanType,
                    suppressionReason: 'knowledge_not_confident'
                );
            }
        }

        // 5. Active Conversation State Conflicts (Clarification, Action, Human Handoff)
        $metadata = $conversation?->metadata ?? [];
        if (!empty($metadata['pending_clarification'])) {
            return new FollowUpDecision(
                allowed: false,
                answer: $cleanAnswer,
                followUpText: $cleanFollowUp,
                followUpType: $cleanType,
                suppressionReason: 'pending_clarification_active'
            );
        }

        if (!empty($metadata['pending_action'])) {
            return new FollowUpDecision(
                allowed: false,
                answer: $cleanAnswer,
                followUpText: $cleanFollowUp,
                followUpType: $cleanType,
                suppressionReason: 'pending_action_active'
            );
        }

        if (!empty($metadata['handoff_to_human'])) {
            return new FollowUpDecision(
                allowed: false,
                answer: $cleanAnswer,
                followUpText: $cleanFollowUp,
                followUpType: $cleanType,
                suppressionReason: 'handoff_active'
            );
        }

        // 6. Complaint, Refund, and Dispute Guard
        if ($this->isComplaintOrDisputeQuery($userQuery)) {
            return new FollowUpDecision(
                allowed: false,
                answer: $cleanAnswer,
                followUpText: $cleanFollowUp,
                followUpType: $cleanType,
                suppressionReason: 'complaint_or_dispute_guard'
            );
        }

        // 7. Explicit User Denial Guard (e.g. "না", "লাগবে না", "no", "not now")
        if ($this->isExplicitDenialQuery($userQuery)) {
            return new FollowUpDecision(
                allowed: false,
                answer: $cleanAnswer,
                followUpText: $cleanFollowUp,
                followUpType: $cleanType,
                suppressionReason: 'user_denial_guard'
            );
        }

        // 8. Action & Security Boundary Guard (Never ask for passwords, credit card numbers, or order mutations)
        if ($this->containsForbiddenActionPattern($cleanFollowUp)) {
            return new FollowUpDecision(
                allowed: false,
                answer: $cleanAnswer,
                followUpText: $cleanFollowUp,
                followUpType: $cleanType,
                suppressionReason: 'forbidden_action_guard'
            );
        }

        // 9. Anti-Repetition & Cooldown Guard
        $followUpState = $metadata['follow_up_state'] ?? null;
        if (is_array($followUpState)) {
            $lastType = $followUpState['last_type'] ?? null;
            $lastText = $followUpState['last_text'] ?? '';
            $status = $followUpState['status'] ?? '';

            // Immediate repetition of identical follow-up text or identical type without turn gap
            if ($lastType === $cleanType && $status === 'asked') {
                return new FollowUpDecision(
                    allowed: false,
                    answer: $cleanAnswer,
                    followUpText: $cleanFollowUp,
                    followUpType: $cleanType,
                    suppressionReason: 'repetition_cooldown_active'
                );
            }

            if ($lastText !== '' && mb_strtolower($lastText) === mb_strtolower($cleanFollowUp)) {
                return new FollowUpDecision(
                    allowed: false,
                    answer: $cleanAnswer,
                    followUpText: $cleanFollowUp,
                    followUpType: $cleanType,
                    suppressionReason: 'duplicate_text_suppressed'
                );
            }
        }

        // 10. General / Store Info Non-CTA Guard (e.g., store hours, general policies with no product context)
        if ($this->isGeneralInfoWithoutProductContext($userQuery, $contextResult)) {
            return new FollowUpDecision(
                allowed: false,
                answer: $cleanAnswer,
                followUpText: $cleanFollowUp,
                followUpType: $cleanType,
                suppressionReason: 'general_info_non_cta'
            );
        }

        // All checks passed -> ALLOW
        return new FollowUpDecision(
            allowed: true,
            answer: $cleanAnswer,
            followUpText: $cleanFollowUp,
            followUpType: $cleanType
        );
    }

    /**
     * Record the follow-up state in conversation metadata upon delivery.
     */
    public function recordFollowUpState(Conversation $conversation, FollowUpDecision $decision): void
    {
        if (!$conversation->exists) {
            return;
        }

        $metadata = $conversation->metadata ?? [];
        if ($decision->isAllowed()) {
            $metadata['follow_up_state'] = [
                'last_type' => $decision->followUpType,
                'last_text' => $decision->followUpText,
                'status'    => 'asked',
                'timestamp' => now()->toIso8601String(),
            ];
        } else {
            // When user asked a new question and follow-up was suppressed, advance state
            if (isset($metadata['follow_up_state'])) {
                $metadata['follow_up_state']['status'] = 'expired';
            }
        }

        $conversation->metadata = $metadata;
        $conversation->save();
    }

    /**
     * Check if query expresses complaint, defect, damage, late delivery, or refund dispute.
     */
    private function isComplaintOrDisputeQuery(string $query): bool
    {
        $q = mb_strtolower(trim($query));
        $patterns = [
            '/(refund|রিফান্ড|টাকা\s*ফেরত)/ui',
            '/(অভিযোগ|complaint|complain|scam|fraud|fake|ভুয়া)/ui',
            '/(damaged|broken|defect|নষ্ট|ভাঙা|ছেঁড়া|ছেড়া|ছেঁড়াখোঁড়া|ছেড়াখোড়া)/ui',
            '/(late\s+delivery|দেরি|দেরিতে|missing\s+item|পায়নি|পাইনি|haraye\s+geche)/ui',
            '/(baje\s+service|faltu|খারাপ|বাজে\s+সার্ভিস)/ui',
        ];

        foreach ($patterns as $p) {
            if (preg_match($p, $q)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Check if query is an explicit refusal/denial of assistance or previous CTA.
     */
    private function isExplicitDenialQuery(string $query): bool
    {
        $q = mb_strtolower(trim($query));
        return (bool) preg_match('/^(না|না,\s*লাগবে\s*না|দরকার\s*নেই|no|not\s+now|no\s+thanks|na|lagbe\s*na|dorkar\s*nai)$/ui', $q)
            || (bool) preg_match('/^(না|no|na)\s*[,.!?]/ui', $q);
    }

    /**
     * Check if proposal attempts unauthorized ACTION mutations or sensitive credential collection.
     */
    private function containsForbiddenActionPattern(string $followUp): bool
    {
        $f = mb_strtolower($followUp);
        return (bool) preg_match('/(password|পাসওয়ার্ড|pin\s*code|পিন\s*কোড|cvv|credit\s*card\s*number|কার্ড\s*নম্বর|বিকাশ\s*পিন)/ui', $f);
    }

    /**
     * Check if query is generic store info (e.g. store hours, branch location) where sales CTA is inappropriate.
     */
    private function isGeneralInfoWithoutProductContext(string $query, ?ContextualResolutionResult $contextResult): bool
    {
        $q = mb_strtolower(trim($query));
        if (preg_match('/(দোকান\s*কয়টায়|কখন\s*বন্ধ|কখন\s*খোলে|opening\s+hour|store\s+hour|branch\s+location|শাখা\s+কোথায়)/ui', $q)) {
            return true;
        }

        return false;
    }
}
