<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Models\Conversation;
use App\Models\Message;
use Illuminate\Http\Request;
use Illuminate\View\View;

class ObservabilityController extends Controller
{
    /**
     * Render the Live Observability & Telemetry Dashboard.
     */
    public function index(Request $request): View
    {
        // 1. Fetch recent outbound messages generated by AI
        $query = Message::where('direction', 'outbound')
            ->whereNotNull('metadata')
            ->with(['conversation.channelAccount.channel'])
            ->latest('id');

        $totalAiResponses = $query->count();
        $messages = (clone $query)->limit(200)->get();
        $recentMessages = $query->paginate(25);

        // 2. Aggregate telemetry from recent 200 outbound messages for live KPI gauges
        $telemetrySample = Message::where('direction', 'outbound')
            ->whereNotNull('metadata')
            ->latest('id')
            ->limit(200)
            ->get();

        $routeCounts = [
            'knowledge' => 0,
            'chat'      => 0,
            'action'    => 0,
            'ood'       => 0,
            'uncertain' => 0,
        ];

        $gateCounts = [
            'confident'    => 0,
            'ambiguous'    => 0,
            'unanswerable' => 0,
            'bypassed'     => 0,
        ];

        $latencies = [];

        foreach ($telemetrySample as $msg) {
            $meta = $msg->metadata ?? [];

            // Route distribution
            $route = strtolower($meta['route'] ?? $meta['router_type'] ?? 'knowledge');
            if (isset($routeCounts[$route])) {
                $routeCounts[$route]++;
            } else {
                $routeCounts['knowledge']++;
            }

            // Answerability Gate distribution
            $gate = $meta['answerability_decision']['status'] ?? $meta['answerability'] ?? null;
            if ($gate && isset($gateCounts[strtolower($gate)])) {
                $gateCounts[strtolower($gate)]++;
            } else {
                $gateCounts['bypassed']++;
            }

            // Latency extraction
            $lat = $meta['total_time_ms'] ?? $meta['latency_ms'] ?? null;
            if ($lat !== null && is_numeric($lat)) {
                $latencies[] = (float) $lat;
            }
        }

        // Calculate latency percentiles
        $p50Latency = 0.0;
        $p95Latency = 0.0;
        $meanLatency = 0.0;

        if (!empty($latencies)) {
            sort($latencies);
            $count = count($latencies);
            $p50Index = (int) floor($count * 0.50);
            $p95Index = (int) floor($count * 0.95);
            $p50Latency = round($latencies[$p50Index] ?? 0.0, 1);
            $p95Latency = round($latencies[$p95Index] ?? 0.0, 1);
            $meanLatency = round(array_sum($latencies) / $count, 1);
        }

        $activeConversationsCount = Conversation::where('status', 'open')->count();
        $totalConversationsCount = Conversation::count();

        return view('admin.observability.index', [
            'totalAiResponses'         => $totalAiResponses,
            'messages'                 => $messages,
            'recentMessages'           => $recentMessages,
            'routeCounts'              => $routeCounts,
            'gateCounts'               => $gateCounts,
            'p50Latency'               => $p50Latency,
            'p95Latency'               => $p95Latency,
            'meanLatency'              => $meanLatency,
            'activeConversationsCount' => $activeConversationsCount,
            'totalConversationsCount'  => $totalConversationsCount,
            'sampleCount'              => $telemetrySample->count(),
        ]);
    }
}
