<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Enums\RoleEnum;
use App\Models\Conversation;
use App\Models\Message;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class ObservabilityController extends Controller
{
    /**
     * Render the Live Observability & Telemetry Dashboard.
     */
    public function index(Request $request): View
    {
        /** @var User|null $user */
        $user = Auth::user();
        $isSuperAdmin = $user && $user->hasRole(RoleEnum::SUPERADMIN->value);
        $workspaceId = $user?->workspace_id;

        // 1. Fetch recent outbound messages generated by AI with workspace scoping
        $query = Message::where('direction', 'outbound')
            ->whereNotNull('metadata')
            ->with(['conversation.channelAccount.channel'])
            ->latest('id');

        if (! $isSuperAdmin && $workspaceId) {
            $query->whereHas('conversation.channelAccount', function ($q) use ($workspaceId) {
                $q->where('workspace_id', $workspaceId);
            });
        }

        $totalAiResponses = (clone $query)->count();
        $messages = (clone $query)->limit(200)->get();
        $recentMessages = (clone $query)->paginate(25);

        // 2. Aggregate telemetry from recent 200 outbound messages for live KPI gauges
        $routeCounts = [
            'knowledge' => 0,
            'chat'      => 0,
            'action'    => 0,
            'ood'       => 0,
            'uncertain' => 0,
        ];

        $gateCounts = [
            'confident'    => 0,
            'ambiguous'    => 0,
            'unanswerable' => 0,
            'bypassed'     => 0,
        ];

        $latencies = [];

        foreach ($messages as $msg) {
            $meta = $msg->metadata ?? [];

            // Route distribution
            $route = strtolower((string) ($meta['route'] ?? $meta['router_type'] ?? 'knowledge'));
            if (isset($routeCounts[$route])) {
                $routeCounts[$route]++;
            } else {
                $routeCounts['knowledge']++;
            }

            // Answerability Gate distribution
            $gate = $meta['answerability_decision']['status'] ?? $meta['answerability'] ?? null;
            if ($gate && isset($gateCounts[strtolower((string) $gate)])) {
                $gateCounts[strtolower((string) $gate)]++;
            } else {
                $gateCounts['bypassed']++;
            }

            // Latency extraction
            $lat = $meta['total_time_ms'] ?? $meta['routing_telemetry']['total_e2e_ms'] ?? $meta['latency_ms'] ?? null;
            if ($lat !== null && is_numeric($lat)) {
                $latencies[] = (float) $lat;
            }
        }

        // Calculate latency percentiles
        $p50Latency = 0.0;
        $p95Latency = 0.0;
        $meanLatency = 0.0;

        if (! empty($latencies)) {
            sort($latencies);
            $count = count($latencies);
            $p50Index = (int) floor($count * 0.50);
            $p95Index = (int) floor($count * 0.95);
            $p50Latency = round($latencies[$p50Index] ?? 0.0, 1);
            $p95Latency = round($latencies[$p95Index] ?? 0.0, 1);
            $meanLatency = round(array_sum($latencies) / $count, 1);
        }

        // Conversation metrics scoped by workspace
        $convQuery = Conversation::query();
        if (! $isSuperAdmin && $workspaceId) {
            $convQuery->whereHas('channelAccount', function ($q) use ($workspaceId) {
                $q->where('workspace_id', $workspaceId);
            });
        }

        $activeConversationsCount = (clone $convQuery)->where('status', 'open')->count();
        $totalConversationsCount = (clone $convQuery)->count();

        return view('admin.observability.index', [
            'totalAiResponses'         => $totalAiResponses,
            'messages'                 => $messages,
            'recentMessages'           => $recentMessages,
            'routeCounts'              => $routeCounts,
            'gateCounts'               => $gateCounts,
            'p50Latency'               => $p50Latency,
            'p95Latency'               => $p95Latency,
            'meanLatency'              => $meanLatency,
            'activeConversationsCount' => $activeConversationsCount,
            'totalConversationsCount'  => $totalConversationsCount,
            'sampleCount'              => $messages->count(),
        ]);
    }
}
